#ifndef CONFIGURATION_H
#define CONFIGURATION_H


#define USER_BAT_CENTER_X 0.0f
#define USER_BAT_CENTER_Y -0.5f
#define USER_BAT_RADIUS 0.12f
#define USER_BAT_NUM_SEGMENTS 30

#define AI_BAT_CENTER_X 0.0f
#define AI_BAT_CENTER_Y 0.5f
#define AI_BAT_RADIUS 0.12f
#define AI_BAT_NUM_SEGMENTS 30

#define PUCK_CENTER_X 0.0f
#define PUCK_CENTER_Y 0.0f
#define PUCK_RADIUS 0.06f
#define PUCK_NUM_SEGMENTS 15

#define USER_INPUT_FACTOR 1.0f
#define MAX_SPEED 0.07f

#define MAX_INTERSECTION_PERCENT 0.96f
#define FRICTION_FORCE 0.0002f

#define WALL_OFFSET 0.0f
#define WALL_WIDTH 0.04f
#define WALL_ROUNDING_RADIUS 0.06f
#define WALL_ROUNDING_NUM_SEGMENTS 5
#define WALL_RECTANGLE_RADIUS 0.02f
#define WALL_RECTANGLE_ROUNDING_NUM_SEGMENTS 30
#define GATE_WIDTH 0.5f

#define MAX_X 1.0f
#define MIN_X -1.0f
#define MAX_Y 1.0f
#define MIN_Y -1.0f

#define ZERO 0.0f
#define PI 3.1415926f


#endif // CONFIGURATION_H
